-- Migration script to populate partner_resource_types
-- Run this in Supabase SQL Editor

-- 1. Create the table (if running manually, otherwise skip if using the separate file)
-- (Included here for completeness of the migration script artifact)
CREATE TABLE IF NOT EXISTS public.partner_resource_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_uuid uuid NOT NULL REFERENCES public.partners(partner_uuid) ON DELETE CASCADE,
    type_name text NOT NULL,
    type_code text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    UNIQUE(partner_uuid, type_code)
);

ALTER TABLE public.partner_resource_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Partner admins manage own types" ON public.partner_resource_types;
CREATE POLICY "Partner admins manage own types" ON public.partner_resource_types
    USING (partner_uuid = public.get_my_partner_uuid());

DROP POLICY IF EXISTS "Superadmins manage all types" ON public.partner_resource_types;
CREATE POLICY "Superadmins manage all types" ON public.partner_resource_types
    USING (public.is_superadmin());

DROP POLICY IF EXISTS "Users view partner types" ON public.partner_resource_types;
CREATE POLICY "Users view partner types" ON public.partner_resource_types
    FOR SELECT
    USING (partner_uuid = public.get_my_partner_uuid());


-- 2. Populate default types for ALL existing partners
DO $$
DECLARE
    r_partner RECORD;
BEGIN
    FOR r_partner IN SELECT partner_uuid FROM public.partners LOOP
        
        -- Insert 'Scrivania'
        INSERT INTO public.partner_resource_types (partner_uuid, type_name, type_code)
        VALUES (r_partner.partner_uuid, 'Scrivania', 'scrivania')
        ON CONFLICT (partner_uuid, type_code) DO NOTHING;

        -- Insert 'Sala Riunioni'
        INSERT INTO public.partner_resource_types (partner_uuid, type_name, type_code)
        VALUES (r_partner.partner_uuid, 'Sala Riunioni', 'sala_riunioni')
        ON CONFLICT (partner_uuid, type_code) DO NOTHING;

    END LOOP;
END;
$$;
