--
-- PostgreSQL database dump
--

\restrict 7nkVZ4hyjYn2fTD6JgYgU7iEVRioX5ES2ozyZwq80GfROboW7bjno4SKhGmgvgy

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: calendar_tokens; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.calendar_tokens (
    id bigint NOT NULL,
    user_id uuid NOT NULL,
    token uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.calendar_tokens OWNER TO postgres;

--
-- Name: TABLE calendar_tokens; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.calendar_tokens IS 'Stores unique tokens for calendar subscription feed authentication';


--
-- Name: calendar_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.calendar_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.calendar_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: calendar_tokens calendar_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.calendar_tokens
    ADD CONSTRAINT calendar_tokens_pkey PRIMARY KEY (id);


--
-- Name: calendar_tokens calendar_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.calendar_tokens
    ADD CONSTRAINT calendar_tokens_token_key UNIQUE (token);


--
-- Name: idx_calendar_tokens_token; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_calendar_tokens_token ON public.calendar_tokens USING btree (token);


--
-- Name: idx_calendar_tokens_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX idx_calendar_tokens_user_id ON public.calendar_tokens USING btree (user_id);


--
-- Name: calendar_tokens update_calendar_tokens_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_calendar_tokens_updated_at BEFORE UPDATE ON public.calendar_tokens FOR EACH ROW EXECUTE FUNCTION public.update_calendar_tokens_updated_at();


--
-- Name: calendar_tokens calendar_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.calendar_tokens
    ADD CONSTRAINT calendar_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;


--
-- Name: calendar_tokens Users can insert own calendar token; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can insert own calendar token" ON public.calendar_tokens FOR INSERT TO authenticated WITH CHECK ((auth.uid() = user_id));


--
-- Name: calendar_tokens Users can update own calendar token; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can update own calendar token" ON public.calendar_tokens FOR UPDATE TO authenticated USING ((auth.uid() = user_id)) WITH CHECK ((auth.uid() = user_id));


--
-- Name: calendar_tokens Users can view own calendar token; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can view own calendar token" ON public.calendar_tokens FOR SELECT TO authenticated USING ((auth.uid() = user_id));


--
-- Name: calendar_tokens; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.calendar_tokens ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE calendar_tokens; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.calendar_tokens TO anon;
GRANT ALL ON TABLE public.calendar_tokens TO authenticated;
GRANT ALL ON TABLE public.calendar_tokens TO service_role;


--
-- Name: SEQUENCE calendar_tokens_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.calendar_tokens_id_seq TO anon;
GRANT ALL ON SEQUENCE public.calendar_tokens_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.calendar_tokens_id_seq TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict 7nkVZ4hyjYn2fTD6JgYgU7iEVRioX5ES2ozyZwq80GfROboW7bjno4SKhGmgvgy

