--
-- PostgreSQL database dump
--

\restrict t4YCUk332nHNOglWPUGVVmcbGjTQ7IsNAecorabGTGaGk29nq1r8hUiFJI308PT

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: invitations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.invitations (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    invitation_uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    partner_uuid uuid NOT NULL,
    invited_role text NOT NULL,
    invited_email text NOT NULL,
    invited_first_name text,
    invited_last_name text,
    custom_message text,
    expires_at timestamp with time zone NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    used_at timestamp with time zone,
    invited_by_user_id uuid,
    cancelled_at timestamp with time zone,
    CONSTRAINT invitations_email_valid CHECK ((invited_email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text)),
    CONSTRAINT invitations_role_check CHECK ((invited_role = ANY (ARRAY['admin'::text, 'user'::text]))),
    CONSTRAINT invitations_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'used'::text, 'expired'::text, 'cancelled'::text])))
);


ALTER TABLE public.invitations OWNER TO postgres;

--
-- Name: invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invitations invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_pkey PRIMARY KEY (id);


--
-- Name: invitations invitations_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_uuid_key UNIQUE (invitation_uuid);


--
-- Name: idx_invitations_cancelled_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_invitations_cancelled_at ON public.invitations USING btree (cancelled_at);


--
-- Name: idx_invitations_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_invitations_email ON public.invitations USING btree (invited_email);


--
-- Name: idx_invitations_expires_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_invitations_expires_at ON public.invitations USING btree (expires_at);


--
-- Name: idx_invitations_partner_uuid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_invitations_partner_uuid ON public.invitations USING btree (partner_uuid);


--
-- Name: idx_invitations_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_invitations_status ON public.invitations USING btree (status);


--
-- Name: idx_invitations_uuid; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_invitations_uuid ON public.invitations USING btree (invitation_uuid);


--
-- Name: invitations update_invitations_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_invitations_updated_at BEFORE UPDATE ON public.invitations FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: invitations invitations_partner_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.invitations
    ADD CONSTRAINT invitations_partner_uuid_fkey FOREIGN KEY (partner_uuid) REFERENCES public.partners(partner_uuid) ON DELETE CASCADE;


--
-- Name: invitations Authorized users update invitations; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Authorized users update invitations" ON public.invitations FOR UPDATE TO authenticated USING (((invited_by_user_id = auth.uid()) OR (public.is_admin() AND (partner_uuid = public.get_my_partner_uuid())) OR public.is_superadmin()));


--
-- Name: invitations Invitations access based on user role and partner; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Invitations access based on user role and partner" ON public.invitations TO authenticated USING ((public.is_superadmin() OR (public.is_admin() AND (partner_uuid = public.get_my_partner_uuid())))) WITH CHECK ((public.is_superadmin() OR (public.is_admin() AND (partner_uuid = public.get_my_partner_uuid()))));


--
-- Name: invitations Read invitation by exact UUID; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Read invitation by exact UUID" ON public.invitations FOR SELECT TO anon, authenticated USING (true);


--
-- Name: invitations; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE invitations; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.invitations TO anon;
GRANT ALL ON TABLE public.invitations TO authenticated;
GRANT ALL ON TABLE public.invitations TO service_role;


--
-- Name: SEQUENCE invitations_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.invitations_id_seq TO anon;
GRANT ALL ON SEQUENCE public.invitations_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.invitations_id_seq TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict t4YCUk332nHNOglWPUGVVmcbGjTQ7IsNAecorabGTGaGk29nq1r8hUiFJI308PT

