--
-- PostgreSQL database dump
--

\restrict MJrb1QqSkV9aKcA8HdDHiU7DW5Tuk9vTA6ByQX9ip9p3NvcZAo7CtToduuoojk5

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.locations (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    location_uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    partner_uuid uuid NOT NULL,
    location_name text NOT NULL,
    address text,
    city text,
    postal_code text,
    country text DEFAULT 'Italy'::text,
    latitude numeric(10,8),
    longitude numeric(11,8),
    phone text,
    email text,
    description text,
    timezone text DEFAULT 'Europe/Rome'::text,
    business_hours jsonb,
    vat_percentage numeric(5,2) DEFAULT 22.00,
    CONSTRAINT check_latitude CHECK (((latitude IS NULL) OR ((latitude >= ('-90'::integer)::numeric) AND (latitude <= (90)::numeric)))),
    CONSTRAINT check_longitude CHECK (((longitude IS NULL) OR ((longitude >= ('-180'::integer)::numeric) AND (longitude <= (180)::numeric)))),
    CONSTRAINT locations_vat_percentage_check CHECK (((vat_percentage >= (0)::numeric) AND (vat_percentage <= (100)::numeric)))
);


ALTER TABLE public.locations OWNER TO postgres;

--
-- Name: COLUMN locations.address; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.address IS 'Street address of the location';


--
-- Name: COLUMN locations.city; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.city IS 'City where the location is situated';


--
-- Name: COLUMN locations.postal_code; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.postal_code IS 'Postal/ZIP code';


--
-- Name: COLUMN locations.country; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.country IS 'Country (defaults to Italy for European format)';


--
-- Name: COLUMN locations.latitude; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.latitude IS 'Latitude coordinate for mapping';


--
-- Name: COLUMN locations.longitude; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.longitude IS 'Longitude coordinate for mapping';


--
-- Name: COLUMN locations.phone; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.phone IS 'Location-specific phone number';


--
-- Name: COLUMN locations.email; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.email IS 'Location-specific email address';


--
-- Name: COLUMN locations.description; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.description IS 'Additional location details and instructions';


--
-- Name: COLUMN locations.timezone; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.timezone IS 'Timezone for the location';


--
-- Name: COLUMN locations.business_hours; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.business_hours IS 'Business hours in JSON format';


--
-- Name: COLUMN locations.vat_percentage; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.locations.vat_percentage IS 'VAT percentage for this location (0.00-100.00)';


--
-- Name: locations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: locations locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_pkey PRIMARY KEY (id);


--
-- Name: locations locations_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_uuid_key UNIQUE (location_uuid);


--
-- Name: idx_locations_city; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_locations_city ON public.locations USING btree (city) WHERE (city IS NOT NULL);


--
-- Name: idx_locations_coordinates; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_locations_coordinates ON public.locations USING btree (latitude, longitude) WHERE ((latitude IS NOT NULL) AND (longitude IS NOT NULL));


--
-- Name: idx_locations_country; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_locations_country ON public.locations USING btree (country) WHERE (country IS NOT NULL);


--
-- Name: idx_locations_partner; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_locations_partner ON public.locations USING btree (partner_uuid);


--
-- Name: locations update_locations_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_locations_updated_at BEFORE UPDATE ON public.locations FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: locations locations_partner_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.locations
    ADD CONSTRAINT locations_partner_fkey FOREIGN KEY (partner_uuid) REFERENCES public.partners(partner_uuid) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: locations Authenticated users can delete locations; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Authenticated users can delete locations" ON public.locations FOR DELETE USING ((auth.role() = 'authenticated'::text));


--
-- Name: locations Authenticated users can insert locations; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Authenticated users can insert locations" ON public.locations FOR INSERT WITH CHECK ((auth.role() = 'authenticated'::text));


--
-- Name: locations Authenticated users can update locations; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Authenticated users can update locations" ON public.locations FOR UPDATE USING ((auth.role() = 'authenticated'::text));


--
-- Name: locations Users can view locations; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users can view locations" ON public.locations FOR SELECT USING (true);


--
-- Name: locations; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE locations; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.locations TO anon;
GRANT ALL ON TABLE public.locations TO authenticated;
GRANT ALL ON TABLE public.locations TO service_role;


--
-- Name: SEQUENCE locations_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.locations_id_seq TO anon;
GRANT ALL ON SEQUENCE public.locations_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.locations_id_seq TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict MJrb1QqSkV9aKcA8HdDHiU7DW5Tuk9vTA6ByQX9ip9p3NvcZAo7CtToduuoojk5

