--
-- PostgreSQL database dump
--

\restrict jZIwumj6kQGgCXpNHGk5JgWBErQDMpIj0UttR7KrOwMV0eEGaaCZwSKGgQvDE8c

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: partners; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partners (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    first_name text NOT NULL,
    partner_uuid uuid DEFAULT gen_random_uuid() NOT NULL,
    address text,
    zip text,
    city text,
    country text,
    email text,
    piva text,
    contract_template text,
    privacy1 boolean DEFAULT true NOT NULL,
    privacy2 boolean DEFAULT false NOT NULL,
    privacy3 boolean DEFAULT false NOT NULL,
    pec text,
    sid text,
    partner_type text,
    partner_status text DEFAULT 'active'::text NOT NULL,
    company_name text,
    phone text,
    logo_url text,
    website text,
    billing_email text,
    billing_address text,
    billing_zip text,
    billing_city text,
    billing_country text,
    second_name text,
    onboarding_completed boolean DEFAULT false NOT NULL,
    onboarding_steps jsonb DEFAULT '{"resources_added": false, "service_created": false, "location_created": false}'::jsonb,
    fattureincloud_enabled boolean DEFAULT false,
    fattureincloud_api_token text,
    fattureincloud_company_id text,
    fattureincloud_default_vat integer DEFAULT 22,
    fattureincloud_document_type text DEFAULT 'proforma'::text,
    structure_name text,
    CONSTRAINT partners_email_valid CHECK ((email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text)),
    CONSTRAINT partners_partner_status_check CHECK ((partner_status = ANY (ARRAY['active'::text, 'inactive'::text, 'suspended'::text, 'pending'::text])))
);


ALTER TABLE public.partners OWNER TO postgres;

--
-- Name: COLUMN partners.onboarding_completed; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.partners.onboarding_completed IS 'True when partner has completed the initial onboarding tour';


--
-- Name: COLUMN partners.onboarding_steps; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.partners.onboarding_steps IS 'JSON object tracking individual onboarding steps completion: {"location_created": boolean, "resources_added": boolean, "service_created": boolean}';


--
-- Name: partners_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.partners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partners partners_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT partners_email_key UNIQUE (email);


--
-- Name: partners partners_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT partners_pkey PRIMARY KEY (id);


--
-- Name: partners partners_uuid_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partners
    ADD CONSTRAINT partners_uuid_key UNIQUE (partner_uuid);


--
-- Name: idx_partners_first_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_partners_first_name ON public.partners USING btree (first_name);


--
-- Name: idx_partners_onboarding_completed; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_partners_onboarding_completed ON public.partners USING btree (onboarding_completed);


--
-- Name: idx_partners_second_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_partners_second_name ON public.partners USING btree (second_name);


--
-- Name: idx_partners_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_partners_status ON public.partners USING btree (partner_status);


--
-- Name: idx_partners_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_partners_type ON public.partners USING btree (partner_type);


--
-- Name: partners update_partners_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER update_partners_updated_at BEFORE UPDATE ON public.partners FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();


--
-- Name: partners Admins update own partner; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Admins update own partner" ON public.partners FOR UPDATE TO authenticated USING ((public.is_admin() AND (partner_uuid = public.get_my_partner_uuid())));


--
-- Name: partners Admins view own partner; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Admins view own partner" ON public.partners FOR SELECT TO authenticated USING ((partner_uuid = public.get_my_partner_uuid()));


--
-- Name: partners Superadmins manage partners; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Superadmins manage partners" ON public.partners TO authenticated USING (public.is_superadmin());


--
-- Name: partners Superadmins view all partners; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Superadmins view all partners" ON public.partners FOR SELECT TO authenticated USING (public.is_superadmin());


--
-- Name: partners; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE partners; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.partners TO anon;
GRANT ALL ON TABLE public.partners TO authenticated;
GRANT ALL ON TABLE public.partners TO service_role;


--
-- Name: SEQUENCE partners_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.partners_id_seq TO anon;
GRANT ALL ON SEQUENCE public.partners_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.partners_id_seq TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict jZIwumj6kQGgCXpNHGk5JgWBErQDMpIj0UttR7KrOwMV0eEGaaCZwSKGgQvDE8c

