-- Create partner_resource_types table
CREATE TABLE public.partner_resource_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_uuid uuid NOT NULL REFERENCES public.partners(partner_uuid) ON DELETE CASCADE,
    type_name text NOT NULL,
    type_code text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    UNIQUE(partner_uuid, type_code)
);

-- Enable RLS
ALTER TABLE public.partner_resource_types ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Partner admins manage own types" ON public.partner_resource_types
    USING (partner_uuid = public.get_my_partner_uuid());

CREATE POLICY "Superadmins manage all types" ON public.partner_resource_types
    USING (public.is_superadmin());

CREATE POLICY "Users view partner types" ON public.partner_resource_types
    FOR SELECT
    USING (partner_uuid = public.get_my_partner_uuid());

-- Trigger for updated_at
CREATE TRIGGER update_partner_resource_types_updated_at 
    BEFORE UPDATE ON public.partner_resource_types 
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
