--
-- PostgreSQL database dump
--

\restrict cftkIUe6JFthQDne2C6ALSfDHS564iJNiEPu4d4uN0daaFcoSYS6csoL3b5DUaX

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: partner_resource_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partner_resource_types (
    id bigint NOT NULL,
    partner_uuid uuid NOT NULL,
    type_name text NOT NULL,
    type_code text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.partner_resource_types OWNER TO postgres;

--
-- Name: partner_resource_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.partner_resource_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partner_resource_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partner_resource_types partner_resource_types_partner_uuid_type_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partner_resource_types
    ADD CONSTRAINT partner_resource_types_partner_uuid_type_code_key UNIQUE (partner_uuid, type_code);


--
-- Name: partner_resource_types partner_resource_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partner_resource_types
    ADD CONSTRAINT partner_resource_types_pkey PRIMARY KEY (id);


--
-- Name: partner_resource_types partner_resource_types_partner_uuid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partner_resource_types
    ADD CONSTRAINT partner_resource_types_partner_uuid_fkey FOREIGN KEY (partner_uuid) REFERENCES public.partners(partner_uuid) ON DELETE CASCADE;


--
-- Name: partner_resource_types Partner admins manage own types; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Partner admins manage own types" ON public.partner_resource_types USING ((partner_uuid = public.get_my_partner_uuid()));


--
-- Name: partner_resource_types Superadmins manage all types; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Superadmins manage all types" ON public.partner_resource_types USING (public.is_superadmin());


--
-- Name: partner_resource_types Users view partner types; Type: POLICY; Schema: public; Owner: postgres
--

CREATE POLICY "Users view partner types" ON public.partner_resource_types FOR SELECT USING ((partner_uuid = public.get_my_partner_uuid()));


--
-- Name: partner_resource_types; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.partner_resource_types ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE partner_resource_types; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.partner_resource_types TO anon;
GRANT ALL ON TABLE public.partner_resource_types TO authenticated;
GRANT ALL ON TABLE public.partner_resource_types TO service_role;


--
-- Name: SEQUENCE partner_resource_types_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.partner_resource_types_id_seq TO anon;
GRANT ALL ON SEQUENCE public.partner_resource_types_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.partner_resource_types_id_seq TO service_role;


--
-- PostgreSQL database dump complete
--

\unrestrict cftkIUe6JFthQDne2C6ALSfDHS564iJNiEPu4d4uN0daaFcoSYS6csoL3b5DUaX

