-- Migration: Create calendar_tokens table for calendar subscription authentication
-- Created: 2026-01-23

-- Create calendar_tokens table
CREATE TABLE IF NOT EXISTS public.calendar_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  token uuid DEFAULT gen_random_uuid() NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Add comment
COMMENT ON TABLE public.calendar_tokens IS 'Stores unique tokens for calendar subscription feed authentication';

-- Create indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_calendar_tokens_user_id ON public.calendar_tokens(user_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_calendar_tokens_token ON public.calendar_tokens(token);

-- Enable RLS
ALTER TABLE public.calendar_tokens ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view own calendar token" 
  ON public.calendar_tokens FOR SELECT 
  TO authenticated 
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own calendar token" 
  ON public.calendar_tokens FOR INSERT 
  TO authenticated 
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own calendar token" 
  ON public.calendar_tokens FOR UPDATE 
  TO authenticated 
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Grants
GRANT ALL ON TABLE public.calendar_tokens TO anon;
GRANT ALL ON TABLE public.calendar_tokens TO authenticated;
GRANT ALL ON TABLE public.calendar_tokens TO service_role;

-- Create trigger for updated_at
CREATE OR REPLACE FUNCTION public.update_calendar_tokens_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_calendar_tokens_updated_at
  BEFORE UPDATE ON public.calendar_tokens
  FOR EACH ROW
  EXECUTE FUNCTION public.update_calendar_tokens_updated_at();
